@token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJub21icmVzIjoiQXBwIiwiYXBlbGxpZG9zIjoiQXBwIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbCI6ImZpc2NhbCIsInVzdWFyaW8iOiJ0ZXN0IiwiaWF0IjoxNzU2NTg0NzU4LCJleHAiOjE3NTcxODk1NTh9.yh9BXVkTgOyKOepcqgejMlN_O5w8v-_RDalmiRSA8dc'
### Login
POST http://api.lalibertadavanzacomuna7.com/api/auth/login
Content-Type: application/json

{
  "usuario": "test",
  "password": "Test123456"
}

### Listar fiscalizaciones #nombre apellido y zona 36293331 11386991 96179932
POST http://api.lalibertadavanzacomuna7.com/api/fiscalizacion/listar
Authorization: {{token}}
Content-Type: application/json

{
    "dni_miembro": "96179932",
    "asignado": true
}

 ### Listar fiscal
POST http://api.lalibertadavanzacomuna7.com/api/fiscalizacion/buscarFiscal
Authorization: {{token}}
Content-Type: application/json1

{
    "dni_miembro": 36293331
}